const domen='https://mis-api.kreosoft.space/api/'
export const registerDocURL=domen+'doctor/register'
export const loginURL=domen+'doctor/login'
export const logoutURL=domen+'doctor/logout'
export const profileURL=domen+'doctor/profile'
export const specialsURL=domen+'dictionary/speciality?page=1&size=5'
export const patientList= domen+'patient'
export const diagList= domen+'dictionary/icd10/roots'
export const inspectionUrl=domen+'inspection'
export const consultUrl=domen+'consultation'
export const diagsListUrl=domen+'dictionary/icd10?page=1&size=5'